### ISSUE TITLE
Please add a link for "Don't forget to polyfill require"

### ISSUE THREAD

**Issue by Pomax** [webpack/json-loader#7]
This statement is absolutely not what someone who's looking for information on why loading json isn't working hopes to find. It just makes them more angry because no one's explaining how the hell to *use* this loader =)

**Comment by dmitry** [comment]
I agree. Related issue: https://github.com/webpack/webpack/issues/140

**Comment by donaldpipowitch** [comment]
+1. I have no idea how to use `var pkg = require('../package.json');` in a Node project. I set `target: 'node'` and `externals: [ /\.json$/ ],`, but it doesn't work. I don't know if json-loader helps me here?

**Comment by donaldpipowitch** [comment]
This doesn't seem to work when I use `require(path.join(process.cwd(), 'package.json'));`. I created a separate issue for that: https://github.com/webpack/webpack/issues/2413

**Comment by Pomax** [comment]
@donaldpipowitch requires with magic names will always be a problem because the bundler has no idea what you're asking for (it would have to actually *run* the code to figure out which thing you're actually requiring) so you're going to have to use relative, explicit strings like `require('./package.json')`.

**Comment by donaldpipowitch** [comment]
I don't want to bundle my JSON file in that case. I want a vanilla Node require. Webpack should do nothing. (I have a _hack_ in webpack/webpack#2413 which works.)

**Comment by Pomax** [comment]
if it's code that will end up in your bundle, there is no vanilla node, because the bundle will run in the browser. If it's code that never ends up bundled in, then you don't need a webpack loader, node already knows how to require .json files

**Comment by donaldpipowitch** [comment]
As mentioned above it is `target: 'node'` and will not be executed in the browser. The JSON should not be bundled, but required at runtime.

> node already knows how to require .json files

That is exactly what I meant with Nodes "vanilla require". I use webpack just for other things then JSON.

**Comment by Pomax** [comment]
in that case I don't quite understand why you're commenting on a thread that is specifically about webpack's json-loader, which is necessary *only* when you need to bundle. If your `require` is in code that doesn't need to be bundled, then this library is not relevant to your needs, but more importantly even if it is, this particular issue --about a README improvement-- has nothing to do with the question you really want to ask. Better to open a new issue, possibly not even on this repo.

**Comment by donaldpipowitch** [comment]
Sorry, I don't know if you read my comments. In my first commend I said "I don't know if json-loader helps me here?". So yes, maybe this was the wrong issue in the first place but nobody corrected me, so I thought I was correct. That was nearly a month ago. _Now_ I know json-loader was the wrong tool for my problem. I DID created a new issue in a different repository. I just commented here for people who look at this loader for the same problem in the first place - just like me. I don't even use json-loader. But if you ask someone how to load JSON in a webpack based Node project, everyone seems to redirect you to this repository as the only valid solution...

You even said "this statement is absolutely not what someone who's looking for information on why loading json isn't working hopes to find." This is what drove me here, too. Loading JSON in a Node project wasn't working for me. However this README doesn't tell what this loader really does (or _not_ does which was more important for me as it turns out). It just says "don't forget the require polyfill". Browsers don't have a `require` which could be polyfilled. Only Node has `require`. So yeah, that's why I thought this missing polyfill was the reason why I couldn't load JSON in Node when using webpack, because I have no clue if webpack alters Nodes `require`. If not, why wouldn't it work (especially with `target: 'node'`), right? Sorry for that! But seriously... I still don't know what this `require` polyfill even does? Why do I need a polyfill for _bundling_ (as in _inlining_) JSON?

**Comment by Pomax** [comment]
but... but this is the `webpack/json-loader` repository. It's *for webpack*, that part should be relatively obvious?

**Comment by rob3c** [comment]
As an alternative to using a `require` polyfill for runtime loading of json resources that you aren't using `json-loader` to inline with webpack for whatever reason (they're too big and you don't want to slow down app loading, they change at runtime, etc.), you might be interested in the solution I posted in response to the issue @donaldpipowitch referenced: https://github.com/webpack/webpack/issues/2413#issuecomment-216381287

**Comment by donaldpipowitch** [comment]
> If you're using webpack to bundle your code and you need to bundle in a json resource, then you want this loader.  If you're not forming a webpacked bundle, then you this library is not what you were looking for.

I _do_ use webpack to bundle code, but this doesn't mean that I want to bundle my JSON, because it isn't static. I just wanted clarify that. It is not either bundling and using webpack or not bundling and don't use webpack. You can use webpack for bundling _most things_ (like your code), but not everything (like _some_ JSON). And it is quite hard to figure out how to opt-out from bundling in _some_ cases.

@rob3c Thanks, I'll look into that.

**Comment by kadamwhite** [comment]
I would like to vote to remove the statement entirely, instead of adding a link, because this sentence makes it seem that if I _do_ want to bundle the JSON with my generated library, then I need to do some additional work in order to make it function in Node environments—which does not seem to be the case.

In webpack/webpack#140 @sokra goes so far as to state "The sentence is pretty old, I should remove it from all the loaders.", indicating this is a legacy of an earlier time.

**Comment by SpaceK33z** [comment]
@kadamwhite thanks for your insights. I've removed the statement.
